#项目服务器配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/geek-temp?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
  redis:
    #redis数据库索引(默认为0)
    database: 0
    #redis服务器地址
    host: 127.0.0.1
    #redis服务器连接端口
    port: 6379
    #redis连接密码
    password: