spring:
  application:
    name: social-admin-api
  profiles:
    active: @spring.profiles.active@
  mvc:
    path-match:
      matching-strategy: ant_path_matcher #解决
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    servlet:
      content-type: text/html     # 模板类型
    cache: true


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.common.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: true # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8081
  servlet:
    context-path: /social-admin-api

logging:
  config: classpath:log/logback-spring.xml

knife4j:
  enable: true  #开启增强功能
  basic:
    enable: true    #开启密码模式
    username: admin   #用户名
    password: 123456  #密码


auth:
  ignore_urls:
    - /sys/auth/**
    - /actuator/**
    - /v3/api-docs/**
    - /webjars/**
    - /swagger/**
    - /swagger-resources/**
    - /swagger-ui.html
    - /swagger-ui/**
    - /doc.html
    - /

aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-hangzhou.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI5tFoq
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: 9dMhgTOSI862
    # oss的存储空间
    bucketName: tnx